# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a51205aab31490243b04b24b6725d9fc88e9dbb01387ae72102a6768206f295372e4ee634eb9a905e155319ac14c834b8c1ce62b5e3042c070cb92f531145d

test:
  secret_key_base: ae422145c9ddcadf598a77746eafe237d6ff95691e3b02cd63641d14bd4a975827d23fdce3527d0342125b72843c8849ab7336d8bd2aa34d0ae8038263ea12fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
